SQL_DDL_HW
gergelyzsolnai/Gergely_Zsolnai_AU24 pull request #11
Opened 2024-11-11 16:06 UTC by gergelyzsolnai

Hello Alena, 

I am ready with the homework. 

Please let me know, if you find issues with it. 

Thank you,
Gergely

2024-11-12 07:25 UTC, gergelyzsolnai commented on SQL_DDL_Gergely_Zsolnai_HW.sql
@DrevinaAlena 
Should i do a little bit of formatting? Because i think some of the lines are too long, and it goes to the next line, and maybe it is hard to read.

2024-11-12 11:36 UTC, DrevinaAlena requested changes
Hi @gergelyzsolnai ,
good job!

Please pay attention to my comments and recommendations:

1) A schema must be created. It serves to organize the tables clearly and allows for better management of database objects.

2) When defining tables, ensure their association with a schema is indicated. 

3) Utilizing BEGIN and COMMIT for the creation of each table is unnecessary within a script.

4) The feature 'GENERATED ALWAYS AS' was skipped. 

5) Opt for 'INSERT INTO ... SELECT' over 'INSERT INTO ... VALUES' for data insertion. This method is advantageous for inserting data dynamically and helps in avoiding duplicate entries efficiently.

6) When inserting data, it is essential to check for duplicates. 

7) use RETURNING *; following your INSERT queries to observe the inserted rows. 

8) There were issues identified when inserting data into the columns: contributor_id, campaign_id, survey_id, and question_id. (null values but you have not null constraint)

Please correct these issues,

Regards,
Alena.

2024-11-12 16:01 UTC, gergelyzsolnai commented
@DrevinaAlena 

Hello Alena,
Thank you, but it seems still having a lot of mistakes. I am on it, thank you for letting me know!

The 4th mistake: The feature 'GENERATED ALWAYS AS' was skipped.

What do you mean? Is it the record_ts, where i should use the feature?

Best wishes,
Gergely

2024-11-12 18:56 UTC, DrevinaAlena commented
@gergelyzsolnai 
![image](https://github.com/user-attachments/assets/b09697df-4622-4367-b91e-b1f687f6e708)

2024-11-14 13:04 UTC, gergelyzsolnai commented
@DrevinaAlena 

Hello Alena, 

I am ready with the modifications. I hope you will find it good too. 

Best regards,
Gergely

2024-11-14 13:11 UTC, DrevinaAlena commented
Hi @gergelyzsolnai ,
1) database and schema must be rerunnable (using if not exists as well)
2) add 'returning *;'   for the table political_schema.contribution_finance
3) it's expected to be seen 'commit;' logically entered in your code (for example after creating tables, after altering, after inserting data))

Regards,
Alena.

2024-11-14 13:37 UTC, gergelyzsolnai commented
@DrevinaAlena 

Yes, i am ready with your suggested 2 and 3. 
But 1st.... i have problems with the altering the new coloumn.... I think my code is rerunnable, exept this. I don't know how to skip addig the column, if it exists. It gets error message, when it gets there.

Maybe if i add the columns when i create the tables.... but the task says, i have to alter them, right?

2024-11-14 13:41 UTC, DrevinaAlena commented
CREATE DATABASE IF NOT EXISTS ...;

CREATE SCHEMA IF NOT EXISTS ...;

2024-11-14 15:40 UTC, gergelyzsolnai commented
@DrevinaAlena 

I did not use 
create database if not exists political_campaign;
Because i got this error message:
SQL Error [42601]: ERROR: syntax error at or near "not"
  Position: 20
  
  I tried it in Dbeaver and also in pgadmin. 
  
  I don't know what is wrong.

2024-11-14 16:55 UTC, DrevinaAlena commented
@gergelyzsolnai 
ok, in this case do please only for schema (if not exists)

2024-11-14 17:13 UTC, gergelyzsolnai commented
@DrevinaAlena 
Thank you!

I uploaded the modified one.

2024-11-14 17:19 UTC, DrevinaAlena approved these changes
Approved,
could be merged.

Regards,
Alena.

2024-11-14 17:23 UTC, gergelyzsolnai commented
Thank you!

2024-11-14 17:23 UTC, merged